### ISSUE TITLE
mvn install error 

### ISSUE THREAD

**Issue by sareenvikalp** [rigarcia/maven-grunt-karma-mocha-tests#1]
Hello thanks for writing it down in github, but here i am facing a small issue while running mvn clean install 

 [INFO] skip non existing resourceDirectory C:\vikalp\BPM\mocha\karma_mocha_grunt\maven-grunt-karma-mocha-tests-master\maven-grunt-karma-mocha-tests-master\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ mocha-tests ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mocha-tests ---
[INFO] No tests to run.
[INFO]
[INFO] --- grunt-maven-plugin:1.5.0:grunt (mocha-tests) @ mocha-tests ---
[INFO] OS Name: Windows 10
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'karma'
Warning: Task "karma:dev" not found. Use --force to continue.

Thanks for help in advance.

**Comment by rauligs** [comment]
I dint' realise it had an issue raised. It seems you haven't installed karma. It is recommended to be installed globally. Is not specified but I'll update the README
